version: '2'
services:
    data:
        image: impactbot/impact-platform-data
        volumes:
            - "./:/data/www"

    blackfire:
        image: blackfire/blackfire
        env_file:
            - env/.dev
        external_links:
            - nginx:myhost

    php-fpm:
        image: impactbot/impact-platform-phpfpm:blackfire-profiling
        volumes_from:
            - data
        ports:
            - "9000"
        env_file:
            - env/.dev
        command:
            - php-fpm
            - -F

    nginx:
        image: impactbot/impact-platform-nginx
        volumes_from:
            - data
        ports:
            - "8080:80"
        depends_on:
            - php-fpm
        volumes:
            - "./sites/:/data/config/sites"

